name: Build to AWS ECR

on: push

jobs:
  configure-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

  build-and-push:
    runs-on: ubuntu-latest
    needs: configure-aws

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Login to AWS Public ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Docker Build and Push
        run: |
          docker build -t awsgithubaction_api .
          docker tag awsgithubaction_api:latest public.ecr.aws/b8y5c4r5/awsgithubaction_api:v1
          docker push public.ecr.aws/b8y5c4r5/awsgithubaction_api:v1
    
        
      
          
        
