name: build to AWS ECR

on: push

jobs: 
  login-to-aws:
    runs-on: ubuntu-latest

    steps: 
      - name: code chechout
        uses: action/checkout@v4
        
      - name: login-aws
        uses: aws-action/configure-aws-credentials@v4
        with: 
          aws-access-key-id: $(( secret.ACCESS_KEY ))
          aws-secret-access-key: $(( secret.SECRET_ACCESS_KEY ))
          aws-region: $(( secret.REGION ))
  
